JaspervanRiet/duck_router

flutter/packages/duck_router/lib/src/duck_router.dart, flutter/packages/duck_router/test/src/duck_router_test.dart
When users add two locations with the same path, e.g. `home` and `home`, the router is unable to handle that. In theory we could add some sort of randomizer to the path, but my judgement in this case is that it would be better to throw an error and have the user set an unique path instead. It would be good to then throw a specific error though. This PR implements that.
Fixes #6
=> feat: catch case where users pushes duplicate path

flutter/packages/duck_router/lib/src/shell.dart, flutter/packages/duck_router/test/src/duck_router_test.dart
This PR fixes an issue where we were not calling the child back button dispatcher to take priority. It was hard to replicate, but the second test this PR contributed fails for the previous code after popping twice.
Closes #5
=> fix: child back button dispatcher

flutter/packages/duck_router/README.md, flutter/packages/duck_router/example/lib/main.dart, flutter/packages/duck_router/lib/src/location.dart, flutter/packages/duck_router/lib/src/shell.dart, flutter/packages/duck_router/test/src/test_helpers.dart
As #11 rightly points out, StatefulChildLocation has no use anymore. Remove it!
#11
=> feat!: remove StatefulChildLocation

flutter/packages/duck_router/lib/src/delegate.dart, flutter/packages/duck_router/lib/src/duck_router.dart, flutter/packages/duck_router/test/src/duck_router_test.dart
#14 made the decision to remove `root()` too quickly. This brings it back, since that function has quite a lot of value. It allows you to revert to the root of any flow, no matter what that root is. Very common on mobile. This PR reverts it.
Fixes #18
=> feat: revert removal of root()

flutter/packages/duck_router/lib/src/delegate.dart, flutter/packages/duck_router/lib/src/shell.dart, flutter/packages/duck_router/test/src/duck_router_test.dart, flutter/packages/duck_router/test/src/test_helpers.dart
Fixes #16 and allows to pop from a nested flow back to the root LocationStack.
#16 
=> feat: allow popping from a nested flow

flutter/packages/duck_router/lib/src/duck_router.dart, flutter/packages/duck_router/lib/src/shell.dart, flutter/packages/duck_router/test/src/duck_router_test.dart
This PR adds an extra parameter to the navigate method, to clear the stack from all previous pages and only add the new page. Consider it a way of adding the Android's `FLAG_ACTIVITY_CLEAR_TOP` flag on an activity.
While this was also possible with `popUntil(<non-existent-page>)` and `navigate(location, replace:true)`, it was not as clean, and most importantly, a duplicate navigation animation could briefly be seen.
This is different from the `root` method, as the root method will reset to the first page in the stack, whereas this method can introduce a new page on it.
When using nested navigation, a user can choose to clear the nested stack, or the root stack with the `root` parameter.
=> feat: add clear stack

flutter/packages/duck_router/lib/src/delegate.dart, flutter/packages/duck_router/lib/src/duck_router.dart, flutter/packages/duck_router/lib/src/shell.dart, flutter/packages/duck_router/test/src/duck_router_test.dart
As mentioned in #24, it was a bit of a weird interface to have to instantiate a new location to use in the popUntil method (especially if this Location needed parameters). So instead, popUntil is now a generic method, where the passed type is the type of the location to pop to.
I was scratching my head a bit for checking whether the passed type was actually a subtype of Location: when forgetting to add the type, the runtime type was just Location, and so it would pop to the first Location it found. Let me know if you can think of a better solution.
#24 
=> feat!: use Location Type for popUntil

flutter/packages/duck_router/lib/src/delegate.dart, flutter/packages/duck_router/lib/src/duck_router.dart, flutter/packages/duck_router/lib/src/location.dart, flutter/packages/duck_router/lib/src/navigator.dart, flutter/packages/duck_router/lib/src/pages/cupertino.dart, flutter/packages/duck_router/lib/src/pages/custom.dart, flutter/packages/duck_router/lib/src/pages/material.dart, flutter/packages/duck_router/lib/src/shell.dart, flutter/packages/duck_router/test/src/duck_router_test.dart, flutter/packages/duck_router/test/src/test_helpers.dart
This PR migrates DuckRouter to the new Page API for popping pages, see https://docs.flutter.dev/release/breaking-changes/navigator-and-page-api. 
The change has a fundamental impact on us. The suggestion made in the breaking change doc is to remove the page from your list of pages. In our case, that would be in DuckNavigator. The problem we have is that DuckNavigator is that's not where we keep state. That's because we use Navigator both in nested and un-nested contexts. We keep state in the DuckShell and in the DuckRouterDelegate. But at that level, we have abstracted away our use of Page. So when Navigator returns us the page that's been popped, we don't really have a use for it, and we cannot find the corresponding Location for it. At that point we have three choices:
- When the …
=> feat!: migrate to onDidRemovePage

flutter/packages/duck_router/README.md, flutter/packages/duck_router/lib/src/duck_router.dart, flutter/packages/duck_router/lib/src/exception.dart, flutter/packages/duck_router/lib/src/location.dart, flutter/packages/duck_router/lib/src/navigator.dart, flutter/packages/duck_router/lib/src/pages/cupertino.dart, flutter/packages/duck_router/lib/src/pages/custom.dart, flutter/packages/duck_router/lib/src/pages/material.dart, flutter/packages/duck_router/test/src/duck_router_test.dart, flutter/packages/duck_router/test/src/test_helpers.dart
This is an iteration upon #28. There, we started supporting Flutter's `onDidRemovePage` callback. However, we had to make a compromise where users had to implement onPopInvoked when overriding Page.
This PR is an iteration on that PR. It removes the need to implement onPopInvoked, it is now handled automatically. We accomplish this by forcing usage of `DuckPage`, and by making `DuckPage` suitable for any type of `Page` via its new `.custom` constructor. 
This is a breaking change, but I believe the last one around this topic. I have provided documentation in the README that should help users implement concepts such as dialogs.
Users can migrate by:
- Replacing their `extends Page` with `extends DuckPage`
- If they were overriding `createRoute` in these children, making sure that they use …
=> feat!: remove need to specify onPopInvoked

flutter/packages/duck_router/README.md, flutter/packages/duck_router/lib/src/configuration.dart, flutter/packages/duck_router/lib/src/duck_router.dart, flutter/packages/duck_router/lib/src/provider.dart, flutter/packages/duck_router/test/src/duck_router_test.dart
While implementing deeplinks with this package, we found that when a deeplink is received, we need to immediately return a Location stack. However, we would instead like to either:
- go through the default app startup, and only after handle the deeplink request
- when the app is active, just call a DeeplinkService, and let that service handle the necessary navigation (if any).
This should already be supported, as per the documentation in the readme: 
> consider keeping the deeplink location in memory and acting upon it later.
Since it is required to return a Location stack, our current workaround is to either return the userSpecifiedInitialLocation, or fetch and return the currentConfiguration.locationStack. It is only due to the Router implementation that this in fact does not trigger a …
=> feat: add support for fire-and-forget deeplink handling

duck_router/README.md, duck_router/example/lib/main.dart, duck_router/lib/src/configuration.dart, duck_router/lib/src/delegate.dart, duck_router/lib/src/duck_router.dart, duck_router/lib/src/navigator.dart, duck_router/lib/src/shell.dart
Currently, it is not possible to use NavigatorObservers with duck_router. I mentioned this once in a previous issue, but did not pursue it.
However, this limitation stayed with me, as in other apps (where we do not use duck_router) we do rely quite heavily on these observers. So this PR is my attempt to support these observers and remove that limitation.
You'll notice that unlike the navigatorObservers property in MaterialApp, my solution requires a builder function to be added. So the callback is really meant to create new instances of the observers.
PS: I know this topic can become quite complex, they did not achieve a satisfying result yet in [go_router either](https://github.com/flutter/flutter/issues/112196), but I believe we can get away with this solution for now.
Does your PR …
=> feat: add support for NavigatorObservers

duck_router/doc/custom-pages.md, duck_router/lib/duck_router.dart, duck_router/lib/src/delegate.dart, duck_router/lib/src/location.dart, duck_router/lib/src/navigator.dart, duck_router/lib/src/pages/custom.dart, duck_router/lib/src/pages/page.dart, duck_router/lib/src/pages/pages.dart, duck_router/test/src/duck_router_test.dart, duck_router/test/src/test_helpers.dart
As documented by #43, we cannot currently await a `navigate` call to a `DuckPage`. This is an issue caused by the fact we do not provide `onPopInvoked` to the `Page` that `DuckPage` overrides. As a result, we do not call `onPop` in our delegate and never get here: https://github.com/JaspervanRiet/duck_router/blob/5390c2bbb9cdb27bcd5bbd1531ed2d874706e797/duck_router/lib/src/configuration.dart#L87
Solving this can use a number of approaches. My approach here has been very similar to the solution in #31: we want to hide most of this complexity. That means not exposing the popping interface to the user. We can do this by constructing a `Page` object builder in the exact same way that `MaterialPage` and `CupertinoPage` are created. This PR does that by no longer inheriting from `Page` in …
=> fix!: allow awaiting custom page navigation

duck_router/doc/custom-pages.md
Pointed out to me by a colleague, there was a small error in our documentation in regards to the custom pages.
/
=> fix outdated documentation

duck_router/lib/src/configuration.dart, duck_router/lib/src/duck_router.dart, duck_router/lib/src/parser.dart, duck_router/lib/src/provider.dart, duck_router/lib/src/state.dart, duck_router/test/src/duck_router_test.dart
When we navigate to a page and await its result, and that page gets replaced, the following pop is no longer listened to.  This PR implements behaviour where popping from a page that replaced another, will still trigger the original `await navigate`. It does so by creating a new mapping between the new incoming location (the one that replaces) and the completer of the original location when replacing.
#47 
=> feat: allow awaiting a page that gets replaced

duck_router/lib/src/delegate.dart, duck_router/lib/src/duck_router.dart, duck_router/test/src/duck_router_test.dart
Introduce a `popRoot` which allows the user to pop the root location even when there are numerous locations being hosted by it. Currently, you would have to pop all those locations first.
Closes #52
=> feat: allow popping root via popRoot

duck_router/lib/src/configuration.dart, duck_router/lib/src/duck_router.dart, duck_router/lib/src/shell.dart, duck_router/test/src/duck_router_test.dart
Scenario:
- Be on page A
- Navigate to page B, and await the result
- Navigate to page C, and clearStack = true
Page A will forever wait for a result.
This PR fixes this scenario. Page A will now receive an exception. 
Open for feedback on whether this should be seen as a breaking change. It has the potential to surface issues in apps.
Fixes #51 
=> fix: throw exception to listeners if clearStack is used

duck_router/doc/stateful-navigation.md, duck_router/lib/src/duck_router.dart, duck_router/lib/src/location.dart
As mentioned in #21, I feel the documentation on StatefulLocation is actually quite hard to use. I wrote most of this code and had a hard time building a login flow inside a bottom sheet, so that says enough. This example should help.
Note: it seems clear to me that this interface is showing its weakness in this example. The overrides, from a developer perspective, do not make sense. I will be trying some experiments to improve things.
#11 
=> docs: describe more details on nested navigation

duck_router/doc/stateful-navigation.md, duck_router/lib/src/location.dart, duck_router/lib/src/pages/page.dart, duck_router/pubspec.yaml, duck_router/test/src/duck_router_test.dart, duck_router/test/src/test_helpers.dart
This PR tackles the difficulty in creating flows, see also #56, and in general some of the complexity in creating nested locations. I tackled this issue by taking an approach of:
- Limiting the methods that can be overridden to only those that can actually be useful, which simplifies the interface. They are `meta` tags, so consumer can ignore the warnings if really needed. Our intention of course is for that not to be needed.
- Renaming methods where useful to make the interface easier to use. I have renamed `pageBuilder` to `containerBuilder`, which I think is much easier to understand. It means you now have a `childBuilder` and a `containerBuilder`. The former builds every child, the latter builds the container around the whole stack. I considered `stackBuilder` for a bit for I feel …
=> feat!: flow locations

duck_router/lib/src/location.dart, duck_router/lib/src/state.dart
Tighten up the API by using the new dart class modifiers to disable usage outside of the package.
=> refactor!: tighten up classes

duck_router/doc/stateful-navigation.md, duck_router/lib/src/duck_router.dart, duck_router/lib/src/location.dart, duck_router/test/src/duck_router_test.dart
I do not find `popRoot` an intuitive name, it's not immediately obvious what its difference with `root` and `pop` is. Thus, introducing `exit`: instantly exit the current navigational stack if currently in a stateful location. See also: #57. I have implemented using deprecation to not break current usages.
=> refactor: deprecate `popRoot` for `exit`

duck_router/lib/duck_router.dart, duck_router/lib/src/delegate.dart, duck_router/lib/src/location.dart
I want to be able to catch `DuckRouterException`s, but they are not exposed. This exposes the Exception.
I think we should also maybe break down the different thrown exceptions into subclassed exceptions, or maybe an enum inside the `DuckRouterException`, to properly catch specific exceptions (I want to catch the exception that occurs when the clearstack is triggered). I see this as a separate PR, how would you tackle this?
/
=> feat: expose DuckRouterException

duck_router/lib/src/configuration.dart, duck_router/lib/src/delegate.dart, duck_router/lib/src/duck_router.dart, duck_router/lib/src/exception.dart, duck_router/lib/src/location.dart, duck_router/lib/src/pages/page.dart, duck_router/test/src/duck_router_test.dart, duck_router/test/src/location_test.dart
I wanted to catch specific exceptions thrown by DuckRouter (when the result can't be returned due to clearing the stack). This led me to an uncomfortable check on the exception message to see if this was the desired exception.
This change should make catching specific exceptions easier, with backwards compatibility.
/
=> refactor: reorganise thrown exceptions

duck_router/lib/src/shell.dart, duck_router/test/src/duck_router_test.dart, duck_router/test/src/test_helpers.dart
Similar to #47 , a navigation result is never returned when replacing the screen we are awaiting the result from. A fix was already implemented when this occurred in the root stack, but was missing when in a nested stack.
#47 
#50 
=> fix: complete completer when replacing in shell

duck_router/lib/src/configuration.dart, duck_router/lib/src/duck_router.dart, duck_router/lib/src/location.dart, duck_router/test/src/restoration_test.dart, duck_router/test/src/test_helpers.dart
We currently support route restoration in the most limited way (paths only). This means arguments are not brought along. This PR introduces `DuckRestorer`, which the user can implement to support restoration in their app. `DuckRestorer` places the complexity of the route translation on the user's side, while abstracting away all the complexity in the routing framework regarding restoration.
#66
=> feat: restoration of location arguments
